import {compile,Player,requiresBox,BOX_MESSAGE} from './engine.mjs';
const $=id=>document.getElementById(id);let worker,ready=false,page=0,request=0,selection=0,current=null,view='home',total=0;const cache=new Map();const areaNames=new Map();
function message(text){$('message').textContent=text;clearTimeout(message.timer);message.timer=setTimeout(()=>$('message').textContent='',6500)}
const player=new Player(s=>{if(s.message){$('playStatus').textContent=s.message;if(s.state==='finished')$('progress').value=1;return}$('playStatus').textContent=({stopped:'Parado',starting:'Preparando áudio',playing:'Reproduzindo',paused:'Pausado'}[s.state]||s.state)+(s.step?` · ${s.step.rest?'Silêncio':(s.step.endHz!==undefined&&s.step.endHz!==s.step.hz?s.step.hz+' → '+s.step.endHz:s.step.hz)+' Hz'} · ${s.index+1}/${s.count} · ${Math.max(0,Math.ceil(s.step.seconds*s.scale-s.elapsed))} s`:'');if(s.step&&!s.step.rest&&Math.min(s.step.hz,s.step.endHz??s.step.hz)<=20)$('playStatus').textContent+=' · Frequência muito baixa: pode não ser audível no alto-falante. Ruído branco é separado.';$('progress').value=s.total?s.position/s.total:0;$('play').textContent=s.state==='paused'?'Continuar':'Iniciar';$('pause').disabled=s.state!=='playing';$('wave').disabled=$('speed').disabled=$('repeat').disabled=s.state!=='stopped';$('play').disabled=s.state==='starting'||s.state==='playing'});
function navigate(next){$('message').textContent='';if(next!==view){player.stop();selection++;}view=next;document.querySelectorAll('.view').forEach(e=>e.classList.remove('active'));document.querySelectorAll('.nb').forEach(e=>e.classList.toggle('active',e.dataset.view===next));if(['home','programas','livre'].includes(next)){$('view-'+next).classList.add('active');if(next==='programas'){init();if(current)mount('programPlayer',compile(current));}if(next==='livre'){$('player').hidden=true}}else{$('view-modulo').classList.add('active');$('moduleName').textContent=({voz:'Voz',video:'Vídeo',foto:'Foto',bio:'Bioimpedância',arquivos:'Arquivos'})[next];$('moduleText').textContent=next==='bio'?'Módulo reservado para integração com aparelho de medição. Nenhuma leitura de bioimpedância é simulada.':next==='arquivos'?'Os programas podem ser exportados individualmente no catálogo. Importação e histórico ainda não foram reconstruídos.':'Módulo reservado para uma etapa posterior. Análise ainda não implementada nesta reconstrução.'}}
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.view)));
function init(){if(worker)return;worker=new Worker('search-worker.js');worker.onmessage=({data})=>{if(data.type==='ready'){ready=true;$('loadStatus').textContent=data.count.toLocaleString('pt-BR')+' programas disponíveis';for(const area of data.areas){areaNames.set(area.id,area.nome);const option=document.createElement('option');option.value=area.id;option.textContent=area.nome;$('area').append(option)}for(const bank of data.banks){const o=document.createElement('option');o.value=o.textContent=bank;$('bank').append(o)}search()}else if(data.type==='results'&&data.request===request){total=data.count;page=data.page;$('count').textContent=total.toLocaleString('pt-BR')+(total===1?' programa encontrado':' programas encontrados');$('page').textContent=`${page+1} / ${Math.max(1,Math.ceil(total/50))}`;$('previous').disabled=page===0;$('next').disabled=(page+1)*50>=total;$('list').replaceChildren();for(const r of data.rows){const b=document.createElement('button');b.className='item';b.textContent=r[1];if(['external','hardware'].includes(r[4])){const small=document.createElement('small');small.textContent='Requer Box gerador de frequências';b.append(small);}if(['external','hardware'].includes(r[4])){b.disabled=true;b.title='Aparelho externo não conectado';}else b.onclick=()=>select(r,b);$('list').append(b)}}else if(data.type==='error'){$('count').textContent=data.message;worker.terminate();worker=null;ready=false}};worker.onerror=()=>{$('count').textContent='Falha ao carregar o banco. Reabra Tratamentos para tentar novamente.';worker.terminate();worker=null;ready=false};worker.postMessage({type:'load'})}
function search(){if(!ready)return;worker.postMessage({type:'search',q:$('search').value,bank:$('bank').value,execution:'',area:$('area').value,page,request:++request})}
$('search').oninput=()=>{page=0;search()};$('bank').onchange=$('area').onchange=()=>{page=0;search()};$('previous').onclick=()=>{page=Math.max(0,page-1);search()};$('next').onclick=()=>{if((page+1)*50<total){page++;search()}};
async function select(r,button){const token=++selection;player.stop();current=null;$('player').hidden=true;$('name').textContent='Carregando programa…';$('export').disabled=true;try{let rows=cache.get(r[3]);if(!rows){const res=await fetch(`data/parte-${String(r[3]).padStart(3,'0')}.json`);if(!res.ok)throw Error('Falha ao carregar o programa');rows=await res.json();cache.set(r[3],rows);if(cache.size>4)cache.delete(cache.keys().next().value)}if(token!==selection)return;current=rows.find(x=>x[0]===r[0]);if(!current)throw Error('Programa não encontrado');document.querySelectorAll('.item').forEach(e=>e.classList.remove('selected'));button.classList.add('selected');$('name').textContent=r[1];$('originalName').textContent=current[1];$('originalNameDetails').hidden=r[1]===current[1];$('areasDetail').textContent=(r[6]||[]).map(id=>areaNames.get(id)||id).join(' · ');$('meta').textContent=`ID ${current[0]} · Banco ${current[2]} · ${current[5]} minutos na fonte · ${current[6]} s por passo · ${current[8]}`;$('commands').textContent=current[4];const plan=compile(current);$('sequence').textContent=(plan.parsed||[]).map((s,i)=>`${i+1}. ${s.raw} · ${s.seconds} s`).join(' / ');$('compatibility').textContent=plan.error||`${plan.steps.length} passos na ordem original · ${Number((plan.totalSeconds/60).toFixed(2))} minutos de execução`;$('export').disabled=false;mount('programPlayer',plan);if(innerWidth<760)$('name').scrollIntoView({block:'start'})}catch(e){if(token===selection){$('name').textContent='Não foi possível abrir';message(e.message)}}}
function mount(container,plan){player.stop();$(container).append($('player'));$('player').hidden=!!plan.error;if(!plan.error){$('wave').value='original';$('speed').value='1';player.scale=1;player.waveOverride='original';player.load(plan)}}
$('prepareFree').onclick=()=>{const hz=Number($('freeHz').value),seconds=Number($('freeSeconds').value);player.stop();if(!Number.isFinite(hz)||hz<=0||requiresBox(hz)){$('player').hidden=true;message(Number.isFinite(hz)&&hz>0?BOX_MESSAGE:'Informe uma frequência positiva.');return}if(!Number.isFinite(seconds)||seconds<1||seconds>86400){$('player').hidden=true;message('Informe duração entre 1 e 86.400 segundos.');return}mount('freePlayer',{steps:[{hz,seconds}],wave:'sine'})};
$('play').onclick=()=>{player.tone=Number($('tone').value)/100;player.noise=Number($('noise').value)/100;player.play()};$('pause').onclick=()=>player.pause();$('stop').onclick=()=>player.stop();$('wave').onchange=e=>player.waveOverride=e.target.value;$('speed').onchange=e=>{player.scale=Number(e.target.value);player.report()};$('repeat').onchange=e=>player.repeat=e.target.checked;
for(const type of ['tone','noise'])$(type).oninput=e=>{player[type]=Number(e.target.value)/100;$(type+'Label').textContent=e.target.value+'%';player.volumes()};
$('export').onclick=()=>{if(!current)return;const blob=new Blob([JSON.stringify({schema:['id','nome','banco','frequencias_numericas_diretas','comandos_spooky_preservados','duracao_minutos','tamanho_passo_segundos','forma_onda','arquivo_origem'],programa:current},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`Quantum_VibraSync_Programa_${current[0]}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
window.addEventListener('pagehide',()=>player.stop());navigate('home');
