import assert from 'node:assert/strict';
import fs from 'node:fs';
import {compile,Player} from '../engine.mjs';
const row=c=>[0,'test','',[],c,0,180,1];
for(const f of [0.1,19,20,18000,19000,20000,25000])assert.equal(compile(row(`440,${f},537`)).code,'external');
for(const f of [20.1,440,537,17999])assert.equal(compile(row(String(f))).code,'audio');
assert.equal(compile(row('0=5,440')).code,'audio');
for(const c of ['440-19000','19000-440','0-440','440-0'])assert.equal(compile(row(c)).code,'external');
const player=new Player(()=>{},()=>{throw Error('Output must not open')});
player.load(compile(row('20,537')));await player.play();assert.equal(player.state,'stopped');
const index=JSON.parse(fs.readFileSync('dist/data/indice.json'));
const codes=new Map(index.map(r=>[r[0],r[4]]));
for(const f of fs.readdirSync('data').filter(f=>/^parte-.*\.json$/.test(f)))for(const r of JSON.parse(fs.readFileSync('data/'+f)))assert.equal(codes.get(r[0]),compile(r).code);
assert.equal(codes.get(89136),'external');
console.log('PASS: limites, varreduras, pausas, bloqueio e 90.893 classificações publicadas');
