import crypto from 'node:crypto';
import assert from 'node:assert/strict';import fs from 'node:fs';import {compile,Player} from '../engine.mjs';
const rows=fs.readdirSync('data').filter(x=>x.startsWith('parte-')).sort().flatMap(f=>JSON.parse(fs.readFileSync('data/'+f)));assert.equal(rows.length,90893);assert.equal(new Set(rows.map(r=>r[0])).size,90893);
const manifest=JSON.parse(fs.readFileSync('manifesto-reconstrucao.json'));assert.equal(crypto.createHash('sha256').update(JSON.stringify(rows)).digest('hex'),manifest.sha256_registros_json);
const row=c=>[0,'teste','',[],c,0,180,1];let valid=0,blocked=0;const reasons={};for(const r of rows){const p=compile(r);assert.notEqual(p.code,'syntax',`ID ${r[0]} ${p.error}`);if(p.error){blocked++;reasons[p.code]=(reasons[p.code]||0)+1}else{valid++;assert(p.steps.every(s=>s.hz<20000&&s.endHz<20000&&s.seconds>0));if(/^[\d.,\s]+$/.test(r[4]))assert.deepEqual(p.steps.map(s=>s.hz),r[4].trim().replace(/,$/,'').split(',').map(Number))}}
assert.deepEqual(compile(row('440,440,880,')).steps.map(s=>s.hz),[440,440,880]);assert.equal(compile(row('100=60,200,300=600,')).totalSeconds,840);assert.deepEqual(compile(row('100-200=60,200-100=30,')).steps.map(s=>[s.hz,s.endHz,s.seconds]),[[100,200,60],[200,100,30]]);assert.deepEqual(compile(row('100 W2,200,300 W1,')).steps.map(s=>s.wave),['square','square','sine']);assert.equal(compile(row('0=20,100,')).steps[0].rest,true);for(const c of ['440,BL10,','440 A9,','440 G1,','L440,','M12,','[C2H4],','BLR3,','20000,','100-25000,'])assert(compile(row(c)).error,c);for(const c of ['1,,2','x','100=0','NaN','100=2=3'])assert.equal(compile(row(c)).code,'syntax');
const events=[];const param=()=>({value:0,setTargetAtTime(){},setValueAtTime(...a){events.push(['set',...a])},linearRampToValueAtTime(...a){events.push(['ramp',...a])}});const node=()=>({connect(){},disconnect(){},start(){},stop(){},gain:param(),frequency:param()});let ctx;const factory=()=>ctx={currentTime:0,sampleRate:48000,destination:{},createOscillator:node,createGain:node,createBuffer:()=>({getChannelData:()=>new Float32Array(10)}),createBufferSource:node,resume:async()=>{},close:async()=>{}};let state;const p=new Player(s=>state=s,factory);p.load(compile(row('100-200=2,440=3,')));await p.play();assert(events.some(e=>e[0]==='ramp'&&e[1]===200));ctx.currentTime=1.03;p.pause();assert(Math.abs(p.position-1)<1e-6);await p.play();ctx.currentTime=1.14;p.tick();assert.equal(p.index,1);ctx.currentTime=4.04;p.tick();assert.equal(state.state,'finished');p.load(compile(row('440=1,')));p.repeat=true;await p.play();ctx.currentTime=2.23;p.tick();assert.equal(p.index,0);assert.equal(p.state,'playing');p.stop();
let resolve;const race=new Player(()=>{},()=>({...factory(),resume:()=>new Promise(r=>resolve=r)}));race.load(compile(row('440')));const pending=race.play();race.stop();resolve();await pending;assert.equal(race.state,'stopped');assert.equal(race.ctx,null);
console.log(JSON.stringify({programas:rows.length,comandos_classificados:90893,reproduziveis:valid,bloqueados:blocked,motivos:reasons,testes_motor:'passou'},null,2));
